#!/bin/bash

dir="$(dirname "$0")"
CODS="$dir/data/codecs.list"

# Install Ubuntu Restricted Extras
function extras {
    # Variables
    PACKAGE=ubuntu-restricted-extras
    NAME="Multimedia Codecs"
    # Check if already installed
    show_info 'Checking if already installed...'
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        show_info $NAME 'is not installed. Proceeding'
        if (whiptail --title "Multimedia Codecs" --yesno "Install Ubuntu Restricted Extras for multimedia playback?" 10 60) then
            # Install
            show_info 'Installing...'
            show_warning 'Requires root privileges'
            sudo apt-get install -y ubuntu-restricted-extras
            # Done
            show_success 'Done.'
        else
            main
        fi
    else
        # Already installed
        show_success 'Already installed.'
        whiptail --title "Finished" --msgbox "$NAME are installed." 8 78
        main
    fi
}

# Install others video and audio codecs
function others {
    i=1
    packages_list=()
    while read pkg ; do
        packages_list+=("${pkg} $i off")
        i=$[i+1]
    done < $CODS

    # Select packages
    eval `resize`
    PACKAGES_SELECT=$(whiptail \
        --title "List of available codecs" \
        --checklist \
        "Select by space key" \
        --separate-output \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        ${packages_list[@]} \
        3>&1 1>&2 2>&3)

    # Install selected packages
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        sudo apt-get install -y --no-install-recommends $PACKAGES_SELECT
        if [[ "cat $PACKAGES_SELECT | grep libdvd-pkg" ]]; then
            sudo dpkg-reconfigure libdvd-pkg
        fi
        show_success 'Done.'

        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            show_success 'Already installed.'
            whiptail --title "Finished" --msgbox "Your preferred development tools are installed." 8 78
            codecs
        else
            whiptail --title "Finished" --msgbox "Installation complete." 8 78
            codecs
        fi
    else
        codecs
    fi
}

# Codecs sub menu
function codecs {
    eval `resize`
    CONF=$(whiptail \
        --notags \
        --title "Configure System" \
        --menu "\nWhat would you like to do?" \
        --cancel-button "Go Back" \
        0 0 0 \
        extras "Install ubuntu-restricted-extras" \
        others "install others video and audio codecs" \
        3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        $CONF
    else
        main
    fi
}
