#!/bin/bash

dir="$(dirname "$0")"
MULTS="$dir/data/multimedias.list"
TOOLS="$dir/data/tools.list"

# Install preferred tools software
# using the list of packages 'data/multimedias.list'
function tools {
    # Get package list
    i=1
    packages_list=()
    while read pkg ; do
        packages_list+=("${pkg} $i off")
        i=$[i+1]
    done < $TOOLS

    # Select packages menu
    PACKAGES_SELECT=$(whiptail \
        --title "List of available software" \
        --checklist \
        "Select by space key" \
        --separate-output \
        0 0 0 \
        ${packages_list[@]} \
        3>&1 1>&2 2>&3)

    # Install selected packages
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        sudo apt-get install -y --no-install-recommends $PACKAGES_SELECT
        show_success 'Done.'

        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            show_success 'Already installed.'
            whiptail --title "Finished" --msgbox "Your preferred development tools are installed." 8 78
            softwares
        else
            whiptail --title "Finished" --msgbox "Installation complete." 8 78
            softwares
        fi
    else
        softwares
    fi
}

# Install preferred multimedia software
# using the list of packages 'data/multimedias.list'
function multimedias {
    # Get package list
    i=1
    packages_list=()
    while read pkg ; do
        packages_list+=("${pkg} $i off")
        i=$[i+1]
    done < $MULTS

    # Select packages menu
    PACKAGES_SELECT=$(whiptail \
        --title "List of available software" \
        --checklist \
        "Select by space key" \
        --separate-output \
        0 0 0 \
        ${packages_list[@]} \
        3>&1 1>&2 2>&3)

    # Install selected packages
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        sudo apt-get install -y --no-install-recommends $PACKAGES_SELECT
        show_success 'Done.'

        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            show_success 'Already installed.'
            whiptail --title "Finished" --msgbox "Your preferred development tools are installed." 8 78
            softwares
        else
            whiptail --title "Finished" --msgbox "Installation complete." 8 78
            softwares
        fi
    else
        softwares
    fi
}

# Software sub menu
function softwares {
    eval `resize`
    CONF=$(whiptail \
        --notags \
        --title "Install thirdparty software" \
        --menu "\nWhat would you like to do?" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        multimedias "Install multimedias softwares" \
        tools       "Install tools softwares" \
        3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        $CONF
    else
        main
    fi
}
